const ROLES = Object.freeze({
  SUPER_ADMIN: 'SUPER_ADMIN',
  HOSPITAL_ADMIN: 'HOSPITAL_ADMIN',
  DOCTOR: 'DOCTOR',
  NURSE: 'NURSE',
  PHARMACIST: 'PHARMACIST',
  LAB_TECHNICIAN: 'LAB_TECHNICIAN',
  RADIOLOGIST: 'RADIOLOGIST',
  RECEPTIONIST: 'RECEPTIONIST',
  ACCOUNTANT: 'ACCOUNTANT',
  PATIENT: 'PATIENT',
});

const USER_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
  PENDING: 'PENDING',
});

const PATIENT_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  DECEASED: 'DECEASED',
});

const GENDERS = Object.freeze(['MALE', 'FEMALE', 'OTHER']);
const BLOOD_GROUPS = Object.freeze(['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-']);

const APPOINTMENT_STATUS = Object.freeze({
  REQUESTED: 'REQUESTED',
  CONFIRMED: 'CONFIRMED',
  CHECKED_IN: 'CHECKED_IN',
  IN_QUEUE: 'IN_QUEUE',
  IN_CONSULTATION: 'IN_CONSULTATION',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  NO_SHOW: 'NO_SHOW',
});

const ACTIVE_APPOINTMENT_STATUSES = Object.freeze([
  APPOINTMENT_STATUS.REQUESTED,
  APPOINTMENT_STATUS.CONFIRMED,
  APPOINTMENT_STATUS.CHECKED_IN,
  APPOINTMENT_STATUS.IN_QUEUE,
  APPOINTMENT_STATUS.IN_CONSULTATION,
]);

const SLOT_STATUS = Object.freeze({
  OPEN: 'OPEN',
  BOOKED: 'BOOKED',
  BLOCKED: 'BLOCKED',
  CANCELLED: 'CANCELLED',
});

const QUEUE_STATUS = Object.freeze({
  WAITING: 'WAITING',
  CALLED: 'CALLED',
  IN_SERVICE: 'IN_SERVICE',
  COMPLETED: 'COMPLETED',
  SKIPPED: 'SKIPPED',
});

const CONSULTATION_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
});

const TRIAGE_LEVELS = Object.freeze({
  CRITICAL: 1,
  URGENT: 2,
  MODERATE: 3,
  LOW: 4,
});

const EMERGENCY_STATUS = Object.freeze({
  ARRIVED: 'ARRIVED',
  TRIAGED: 'TRIAGED',
  WAITING: 'WAITING',
  IN_TREATMENT: 'IN_TREATMENT',
  OBSERVATION: 'OBSERVATION',
  ADMITTED: 'ADMITTED',
  DISCHARGED: 'DISCHARGED',
  TRANSFERRED: 'TRANSFERRED',
});

const LAB_ORDER_STATUS = Object.freeze({
  ORDERED: 'ORDERED',
  SAMPLE_COLLECTED: 'SAMPLE_COLLECTED',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
});

const PRESCRIPTION_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  VERIFIED: 'VERIFIED',
  PARTIALLY_DISPENSED: 'PARTIALLY_DISPENSED',
  DISPENSED: 'DISPENSED',
  CANCELLED: 'CANCELLED',
});

const BED_STATUS = Object.freeze({
  AVAILABLE: 'AVAILABLE',
  OCCUPIED: 'OCCUPIED',
  RESERVED: 'RESERVED',
  CLEANING: 'CLEANING',
  MAINTENANCE: 'MAINTENANCE',
});

const ADMISSION_STATUS = Object.freeze({
  ADMITTED: 'ADMITTED',
  TRANSFERRED: 'TRANSFERRED',
  DISCHARGED: 'DISCHARGED',
  ABSCONDED: 'ABSCONDED',
});

const INVOICE_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  PENDING: 'PENDING',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED',
});

const PAYMENT_STATUS = Object.freeze({
  PENDING: 'PENDING',
  SUCCESSFUL: 'SUCCESSFUL',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
});

const INVENTORY_TRANSACTION_TYPES = Object.freeze({
  PURCHASE: 'PURCHASE',
  DISPENSE: 'DISPENSE',
  RETURN: 'RETURN',
  ADJUSTMENT: 'ADJUSTMENT',
  EXPIRED: 'EXPIRED',
});

const NOTIFICATION_TYPES = Object.freeze({
  APPOINTMENT: 'APPOINTMENT',
  LABORATORY: 'LABORATORY',
  PRESCRIPTION: 'PRESCRIPTION',
  BILLING: 'BILLING',
  ADMISSION: 'ADMISSION',
  DISCHARGE: 'DISCHARGE',
  SYSTEM: 'SYSTEM',
  MESSAGE: 'MESSAGE',
});

const MEDICAL_RECORD_TYPES = Object.freeze({
  CONSULTATION: 'CONSULTATION',
  DIAGNOSIS: 'DIAGNOSIS',
  PRESCRIPTION: 'PRESCRIPTION',
  LAB_RESULT: 'LAB_RESULT',
  IMAGING: 'IMAGING',
  ADMISSION: 'ADMISSION',
  DISCHARGE: 'DISCHARGE',
  VITAL_SIGNS: 'VITAL_SIGNS',
  NURSING_NOTE: 'NURSING_NOTE',
  DOCUMENT: 'DOCUMENT',
});

const AUDIT_ACTIONS = Object.freeze({
  PATIENT_VIEWED: 'PATIENT_VIEWED',
  PATIENT_CREATED: 'PATIENT_CREATED',
  PATIENT_UPDATED: 'PATIENT_UPDATED',
  PATIENT_DELETED: 'PATIENT_DELETED',
  MEDICAL_RECORD_VIEWED: 'MEDICAL_RECORD_VIEWED',
  MEDICAL_RECORD_UPDATED: 'MEDICAL_RECORD_UPDATED',
  CONSULTATION_CREATED: 'CONSULTATION_CREATED',
  CONSULTATION_UPDATED: 'CONSULTATION_UPDATED',
  PRESCRIPTION_CREATED: 'PRESCRIPTION_CREATED',
  PRESCRIPTION_DISPENSED: 'PRESCRIPTION_DISPENSED',
  LAB_RESULT_PUBLISHED: 'LAB_RESULT_PUBLISHED',
  INVOICE_CREATED: 'INVOICE_CREATED',
  PAYMENT_VERIFIED: 'PAYMENT_VERIFIED',
  USER_ROLE_CHANGED: 'USER_ROLE_CHANGED',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  USER_LOGOUT: 'USER_LOGOUT',
  DOCUMENT_DOWNLOADED: 'DOCUMENT_DOWNLOADED',
  ADMISSION_CREATED: 'ADMISSION_CREATED',
  PATIENT_DISCHARGED: 'PATIENT_DISCHARGED',
});

const BILLING_ITEM_TYPES = Object.freeze({
  CONSULTATION: 'CONSULTATION',
  LABORATORY: 'LABORATORY',
  IMAGING: 'IMAGING',
  MEDICATION: 'MEDICATION',
  ADMISSION: 'ADMISSION',
  NURSING: 'NURSING',
  PROCEDURE: 'PROCEDURE',
  OTHER: 'OTHER',
});

const DOCUMENT_CATEGORIES = Object.freeze({
  LAB_REPORT: 'LAB_REPORT',
  IMAGING_REPORT: 'IMAGING_REPORT',
  MEDICAL_DOCUMENT: 'MEDICAL_DOCUMENT',
  DISCHARGE_SUMMARY: 'DISCHARGE_SUMMARY',
  PATIENT_DOCUMENT: 'PATIENT_DOCUMENT',
  INSURANCE: 'INSURANCE',
  OTHER: 'OTHER',
});

const STAFF_TYPES = Object.freeze({
  ACCOUNTANT: 'ACCOUNTANT',
  RECEPTIONIST: 'RECEPTIONIST',
  PHARMACIST: 'PHARMACIST',
  LAB_TECHNICIAN: 'LAB_TECHNICIAN',
  RADIOLOGIST: 'RADIOLOGIST',
  ADMINISTRATIVE: 'ADMINISTRATIVE',
});

module.exports = {
  ROLES,
  USER_STATUS,
  PATIENT_STATUS,
  GENDERS,
  BLOOD_GROUPS,
  APPOINTMENT_STATUS,
  ACTIVE_APPOINTMENT_STATUSES,
  SLOT_STATUS,
  QUEUE_STATUS,
  CONSULTATION_STATUS,
  TRIAGE_LEVELS,
  EMERGENCY_STATUS,
  LAB_ORDER_STATUS,
  PRESCRIPTION_STATUS,
  BED_STATUS,
  ADMISSION_STATUS,
  INVOICE_STATUS,
  PAYMENT_STATUS,
  INVENTORY_TRANSACTION_TYPES,
  NOTIFICATION_TYPES,
  MEDICAL_RECORD_TYPES,
  AUDIT_ACTIONS,
  BILLING_ITEM_TYPES,
  DOCUMENT_CATEGORIES,
  STAFF_TYPES,
};