/**
 * Role definitions and the permission matrix used by `authorize` middleware.
 * Permissions are stored in the `permissions` table (see seeders) and mirrored
 * here so that authorisation never requires a database round trip per request.
 */
const { ROLES } = require('../config/constants');

const P = {
  PATIENT_CREATE: 'patients:create',
  PATIENT_READ: 'patients:read',
  PATIENT_UPDATE: 'patients:update',
  PATIENT_DELETE: 'patients:delete',
  MEDICAL_RECORD_READ: 'medical_records:read',
  MEDICAL_RECORD_WRITE: 'medical_records:write',
  DEPARTMENT_READ: 'departments:read',
  DEPARTMENT_MANAGE: 'departments:manage',
  STAFF_READ: 'staff:read',
  STAFF_MANAGE: 'staff:manage',
  APPOINTMENT_CREATE: 'appointments:create',
  APPOINTMENT_READ: 'appointments:read',
  APPOINTMENT_UPDATE: 'appointments:update',
  APPOINTMENT_MANAGE: 'appointments:manage',
  QUEUE_READ: 'queue:read',
  QUEUE_MANAGE: 'queue:manage',
  CONSULTATION_READ: 'consultations:read',
  CONSULTATION_WRITE: 'consultations:write',
  DIAGNOSIS_WRITE: 'diagnoses:write',
  LAB_ORDER_READ: 'lab_orders:read',
  LAB_ORDER_WRITE: 'lab_orders:write',
  LAB_RESULT_WRITE: 'lab_results:write',
  LAB_RESULT_PUBLISH: 'lab_results:publish',
  IMAGING_READ: 'imaging:read',
  IMAGING_WRITE: 'imaging:write',
  PRESCRIPTION_READ: 'prescriptions:read',
  PRESCRIPTION_WRITE: 'prescriptions:write',
  PHARMACY_DISPENSE: 'pharmacy:dispense',
  PHARMACY_INVENTORY: 'pharmacy:inventory',
  ADMISSION_READ: 'admissions:read',
  ADMISSION_MANAGE: 'admissions:manage',
  BED_MANAGE: 'beds:manage',
  NURSING_READ: 'nursing:read',
  NURSING_WRITE: 'nursing:write',
  EMERGENCY_READ: 'emergency:read',
  EMERGENCY_MANAGE: 'emergency:manage',
  BILLING_READ: 'billing:read',
  BILLING_MANAGE: 'billing:manage',
  PAYMENT_VERIFY: 'payments:verify',
  INSURANCE_READ: 'insurance:read',
  INSURANCE_MANAGE: 'insurance:manage',
  NOTIFICATION_READ: 'notifications:read',
  MESSAGE_SEND: 'messages:send',
  MESSAGE_READ: 'messages:read',
  DOCUMENT_UPLOAD: 'documents:upload',
  DOCUMENT_READ: 'documents:read',
  AUDIT_READ: 'audit:read',
  DASHBOARD_ADMIN: 'dashboard:admin',
  DASHBOARD_DOCTOR: 'dashboard:doctor',
  DASHBOARD_PHARMACY: 'dashboard:pharmacy',
  DASHBOARD_LAB: 'dashboard:lab',
  DASHBOARD_NURSE: 'dashboard:nurse',
  USER_MANAGE: 'users:manage',
};

const CLINICAL_READ = [
  P.PATIENT_READ,
  P.MEDICAL_RECORD_READ,
  P.DEPARTMENT_READ,
  P.APPOINTMENT_READ,
  P.QUEUE_READ,
  P.CONSULTATION_READ,
  P.LAB_ORDER_READ,
  P.LAB_RESULT_WRITE,
  P.IMAGING_READ,
  P.PRESCRIPTION_READ,
  P.PRESCRIPTION_WRITE,
  P.DIAGNOSIS_WRITE,
  P.NURSING_READ,
  P.NURSING_WRITE,
  P.MEDICAL_RECORD_WRITE,
  P.ADMISSION_READ,
  P.BILLING_READ,
  P.DOCUMENT_READ,
  P.DOCUMENT_UPLOAD,
  P.NOTIFICATION_READ,
  P.MESSAGE_SEND,
  P.MESSAGE_READ,
];

const ALL_PERMISSIONS = Object.freeze(Object.values(P));

const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.SUPER_ADMIN]: ALL_PERMISSIONS,

  [ROLES.HOSPITAL_ADMIN]: [
    P.PATIENT_CREATE,
    P.PATIENT_READ,
    P.PATIENT_UPDATE,
    P.PATIENT_DELETE,
    P.MEDICAL_RECORD_READ,
    P.DEPARTMENT_READ,
    P.DEPARTMENT_MANAGE,
    P.STAFF_READ,
    P.STAFF_MANAGE,
    P.APPOINTMENT_CREATE,
    P.APPOINTMENT_READ,
    P.APPOINTMENT_UPDATE,
    P.APPOINTMENT_MANAGE,
    P.QUEUE_READ,
    P.QUEUE_MANAGE,
    P.CONSULTATION_READ,
    P.LAB_ORDER_READ,
    P.LAB_RESULT_PUBLISH,
    P.IMAGING_READ,
    P.PRESCRIPTION_READ,
    P.ADMISSION_READ,
    P.ADMISSION_MANAGE,
    P.BED_MANAGE,
    P.NURSING_READ,
    P.EMERGENCY_READ,
    P.EMERGENCY_MANAGE,
    P.BILLING_READ,
    P.BILLING_MANAGE,
    P.PAYMENT_VERIFY,
    P.INSURANCE_READ,
    P.INSURANCE_MANAGE,
    P.NOTIFICATION_READ,
    P.MESSAGE_SEND,
    P.MESSAGE_READ,
    P.DOCUMENT_READ,
    P.AUDIT_READ,
    P.DASHBOARD_ADMIN,
    P.DASHBOARD_DOCTOR,
    P.DASHBOARD_PHARMACY,
    P.DASHBOARD_LAB,
    P.DASHBOARD_NURSE,
    P.USER_MANAGE,
  ],

  [ROLES.DOCTOR]: [
    ...CLINICAL_READ,
    P.PATIENT_CREATE,
    P.APPOINTMENT_CREATE,
    P.APPOINTMENT_UPDATE,
    P.QUEUE_MANAGE,
    P.EMERGENCY_READ,
    P.EMERGENCY_MANAGE,
    P.ADMISSION_MANAGE,
    P.BILLING_READ,
    P.DASHBOARD_DOCTOR,
  ],

  [ROLES.NURSE]: [
    P.PATIENT_READ,
    P.MEDICAL_RECORD_READ,
    P.DEPARTMENT_READ,
    P.APPOINTMENT_READ,
    P.QUEUE_READ,
    P.QUEUE_MANAGE,
    P.CONSULTATION_READ,
    P.LAB_ORDER_READ,
    P.PRESCRIPTION_READ,
    P.ADMISSION_READ,
    P.NURSING_READ,
    P.NURSING_WRITE,
    P.DOCUMENT_UPLOAD,
    P.DOCUMENT_READ,
    P.NOTIFICATION_READ,
    P.MESSAGE_SEND,
    P.MESSAGE_READ,
    P.DASHBOARD_NURSE,
  ],

  [ROLES.PHARMACIST]: [
    P.PATIENT_READ,
    P.DEPARTMENT_READ,
    P.PRESCRIPTION_READ,
    P.PRESCRIPTION_WRITE,
    P.PHARMACY_DISPENSE,
    P.PHARMACY_INVENTORY,
    P.BILLING_READ,
    P.NOTIFICATION_READ,
    P.MESSAGE_SEND,
    P.MESSAGE_READ,
    P.DASHBOARD_PHARMACY,
  ],

  [ROLES.LAB_TECHNICIAN]: [
    P.PATIENT_READ,
    P.MEDICAL_RECORD_READ,
    P.DEPARTMENT_READ,
    P.LAB_ORDER_READ,
    P.LAB_ORDER_WRITE,
    P.LAB_RESULT_WRITE,
    P.ADMISSION_READ,
    P.DOCUMENT_UPLOAD,
    P.DOCUMENT_READ,
    P.NOTIFICATION_READ,
    P.MESSAGE_SEND,
    P.MESSAGE_READ,
    P.DASHBOARD_LAB,
  ],

  [ROLES.RADIOLOGIST]: [
    P.PATIENT_READ,
    P.MEDICAL_RECORD_READ,
    P.DEPARTMENT_READ,
    P.LAB_ORDER_READ,
    P.IMAGING_READ,
    P.IMAGING_WRITE,
    P.LAB_RESULT_PUBLISH,
    P.ADMISSION_READ,
    P.DOCUMENT_UPLOAD,
    P.DOCUMENT_READ,
    P.NOTIFICATION_READ,
    P.MESSAGE_SEND,
    P.MESSAGE_READ,
  ],

  [ROLES.RECEPTIONIST]: [
    P.PATIENT_CREATE,
    P.PATIENT_READ,
    P.PATIENT_UPDATE,
    P.DEPARTMENT_READ,
    P.STAFF_READ,
    P.APPOINTMENT_CREATE,
    P.APPOINTMENT_READ,
    P.APPOINTMENT_UPDATE,
    P.QUEUE_READ,
    P.QUEUE_MANAGE,
    P.ADMISSION_READ,
    P.BILLING_READ,
    P.INSURANCE_READ,
    P.NOTIFICATION_READ,
    P.MESSAGE_SEND,
    P.MESSAGE_READ,
    P.DOCUMENT_UPLOAD,
  ],

  [ROLES.ACCOUNTANT]: [
    P.PATIENT_READ,
    P.DEPARTMENT_READ,
    P.BILLING_READ,
    P.BILLING_MANAGE,
    P.PAYMENT_VERIFY,
    P.INSURANCE_READ,
    P.INSURANCE_MANAGE,
    P.NOTIFICATION_READ,
    P.MESSAGE_SEND,
    P.MESSAGE_READ,
    P.DASHBOARD_ADMIN,
  ],

  // A patient may only ever read/write *their own* records. That ownership check
  // is enforced in the service layer (see `assertPatientAccess`).
  [ROLES.PATIENT]: [
    P.MEDICAL_RECORD_READ,
    P.APPOINTMENT_CREATE,
    P.APPOINTMENT_READ,
    P.QUEUE_READ,
    P.CONSULTATION_READ,
    P.LAB_ORDER_READ,
    P.IMAGING_READ,
    P.PRESCRIPTION_READ,
    P.BILLING_READ,
    P.INSURANCE_READ,
    P.NOTIFICATION_READ,
    P.MESSAGE_SEND,
    P.MESSAGE_READ,
    P.DOCUMENT_UPLOAD,
    P.DOCUMENT_READ,
  ],
});

/** Roles whose users are considered internal staff. */
const STAFF_ROLES = Object.freeze(
  Object.values(ROLES).filter((role) => role !== ROLES.PATIENT),
);

/** Roles allowed to see clinical detail of any patient. */
const CLINICAL_ROLES = Object.freeze([
  ROLES.SUPER_ADMIN,
  ROLES.HOSPITAL_ADMIN,
  ROLES.DOCTOR,
  ROLES.NURSE,
  ROLES.PHARMACIST,
  ROLES.LAB_TECHNICIAN,
  ROLES.RADIOLOGIST,
]);

const RADIOLOGY_ROLES = Object.freeze([ROLES.RADIOLOGIST, ROLES.DOCTOR, ROLES.SUPER_ADMIN]);

/** Human readable text stored alongside each permission row. */
const PERMISSION_DESCRIPTIONS = Object.freeze(
  Object.fromEntries(ALL_PERMISSIONS.map((permission) => [permission, `Allows the ${permission.split(':')[1]} action on ${permission.split(':')[0]}`])),
);

module.exports = {
  P,
  ALL_PERMISSIONS,
  ROLE_PERMISSIONS,
  PERMISSION_DESCRIPTIONS,
  STAFF_ROLES,
  CLINICAL_ROLES,
  RADIOLOGY_ROLES,
};