/**
 * Maps the string keys used in content/hospital.js to icon components.
 * Keeps editorial content free of JSX imports.
 */
import {
  IconActivity,
  IconAward,
  IconBed,
  IconBuilding,
  IconChat,
  IconClipboard,
  IconFile,
  IconFlask,
  IconHeart,
  IconHeartPulse,
  IconMicroscope,
  IconPill,
  IconScan,
  IconShield,
  IconStethoscope,
  IconSyringe,
  IconUsers,
  IconVideo,
  IconWallet,
  IconAmbulance,
  IconCheck,
  IconMapPin,
  IconClock,
  IconCalendar,
  IconPhone,
  IconArrowRight,
  IconCart,
  IconPlus,
  IconX,
  IconSearch,
  IconStar,
  IconGrid,
  IconUser,
  IconBell,
  IconLogout,
  IconSettings,
  IconDownload,
  IconUpload,
  IconMail,
  IconInfo,
  IconLock,
  IconEye,
  IconHome,
  IconChevronRight,
  IconChevronLeft,
  IconChevronDown,
  IconRefresh,
  IconExternal,
  IconFilter,
  IconTrendUp,
  IconClipboard as IconClipboardDoc,
  IconWallet as IconWalletDoc,
  IconNotes,
  IconVideo as IconVideoCall,
} from './Icon';

export const ICONS = {
  activity: IconActivity,
  ambulance: IconAmbulance,
  arrowRight: IconArrowRight,
  award: IconAward,
  bed: IconBed,
  bell: IconBell,
  building: IconBuilding,
  cart: IconCart,
  check: IconCheck,
  chat: IconChat,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  chevronDown: IconChevronDown,
  clipboard: IconClipboard,
  clock: IconClock,
  calendar: IconCalendar,
  download: IconDownload,
  external: IconExternal,
  eye: IconEye,
  file: IconFile,
  filter: IconFilter,
  flask: IconFlask,
  grid: IconGrid,
  heart: IconHeart,
  'heart-pulse': IconHeartPulse,
  home: IconHome,
  info: IconInfo,
  mail: IconMail,
  lock: IconLock,
  logout: IconLogout,
  mapPin: IconMapPin,
  microscope: IconMicroscope,
  notes: IconNotes,
  phone: IconPhone,
  pill: IconPill,
  plus: IconPlus,
  refresh: IconRefresh,
  scan: IconScan,
  search: IconSearch,
  settings: IconSettings,
  shield: IconShield,
  star: IconStar,
  stethoscope: IconStethoscope,
  syringe: IconSyringe,
  trendUp: IconTrendUp,
  upload: IconUpload,
  user: IconUser,
  users: IconUsers,
  video: IconVideo,
  videoCall: IconVideoCall,
  wallet: IconWallet,
  x: IconX,
};

export default ICONS;
